### ISSUE TITLE
Smoothening error

### ISSUE THREAD

**Issue by ADIMANV** [openclimatefix/quartz-mailer#6]
## Describe the bug
Due to the smoothing that takes the internal dashboard, the data that we send and the data that we have dont matchup and have gaps, which cause a difference in the error calculation between us and our client. A fix will ensure that both the parties have the same datasets.
 

## Expected behavior
The datasets being sent from OCF and the data that we access through dashboard will be the same throughout

**Comment by peterdudfield** [comment]
DA smooething has now been turned off with india-api 0.1.36
